name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Change ownership of work directory
      run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/backend/backend

    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # - run: sudo rm -rf /home/ubuntu/actions-runner/_work/backend/backend/build

    - run: npm ci
    - run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}"  > .env

    - run: sudo npm run build

    - run: pm2 stop all

    - run: pm2 start build/index.js --name=api
